CREATE SCHEMA IF NOT EXISTS jippy_mart;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS jippy_mart.mart_sub_category
(
    mart_sub_category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sub_category_name character varying(100) NOT NULL,
    category_id integer NOT NULL, -- get from jippy_fm.category
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT mart_sub_category_pkey PRIMARY KEY (mart_sub_category_id)

);

CREATE TABLE IF NOT EXISTS jippy_mart.mart_products
(
    mart_products_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_id integer NOT NULL,
    mart_sub_category_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    description character varying(500),
    minimum_price NUMERIC(10, 2) NOT NULL, --100.00,120, 200
    maximum_price NUMERIC(10, 2) NOT NULL,-- 105.00,125, 205
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer,
    CONSTRAINT mart_products_pkey PRIMARY KEY (mart_products_id)

);


CREATE TABLE IF NOT EXISTS jippy_mart.order_transactions (
    order_transactions_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id CHARACTER VARYING(30) NOT NULL,
    gateway_payment_id  CHARACTER VARYING(255),                           -- Holds Razorpay Payment ID or Paytm TXNID
    gateway_type CHARACTER VARYING(50) NOT NULL,                                 -- e.g., 'RAZORPAY', 'PAYTM'
    payment_status  CHARACTER VARYING(50) DEFAULT 'PENDING',               -- PENDING, SUCCESS, FAILED, REFUNDED
    amount integer NOT NULL,                                        -- Stored in Paise/Lowest denomination (Integer)
    txn_rrn  CHARACTER VARYING(100),                                       -- Razorpay rrn / Paytm BANKTXNID
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT order_transactions_pkey PRIMARY KEY (order_transactions_id)
);
